// SPDX-License-Identifier: MIT
//
// The browser frontend is the one part of this project a compiler never sees.
// The engine is C++ built with -Wall -Wextra -Wpedantic -Wshadow -Werror on four
// toolchains; app.js is seventeen hundred lines that, until this file existed,
// nothing checked at all — a misspelt identifier reached players as a blank
// screen. This is the closest thing to that compiler that JavaScript has.
//
// Deliberately no package.json and no node_modules in the repository. CI runs
// `npx --yes eslint@9 .`, which needs nothing checked in and leaves a C++
// project without a JavaScript toolchain to maintain. For the same reason the
// browser globals are written out below rather than pulled from the `globals`
// package: one dependency fewer, and the list doubles as a statement of what
// the page is allowed to touch.
//
// The rule set is correctness only. No style rules: the code has a consistent
// voice already, and a formatter argument is not what this file is for.

const browser = {
  window: 'readonly', document: 'readonly', navigator: 'readonly',
  location: 'readonly', history: 'readonly', screen: 'readonly',
  localStorage: 'readonly', sessionStorage: 'readonly',
  console: 'readonly', performance: 'readonly',
  setTimeout: 'readonly', clearTimeout: 'readonly',
  setInterval: 'readonly', clearInterval: 'readonly',
  requestAnimationFrame: 'readonly', cancelAnimationFrame: 'readonly',
  fetch: 'readonly', Image: 'readonly', Blob: 'readonly', URL: 'readonly',
  AudioContext: 'readonly', webkitAudioContext: 'readonly',
  OfflineAudioContext: 'readonly',
  CustomEvent: 'readonly', Event: 'readonly', KeyboardEvent: 'readonly',
  TouchEvent: 'readonly', MouseEvent: 'readonly',
  devicePixelRatio: 'readonly', matchMedia: 'readonly',
  atob: 'readonly', btoa: 'readonly', alert: 'readonly',
};

// What the page's own files hand each other. sprites.js and music.js are
// loaded before app.js; nav.js defines NavModule.
const own = {
  NAV_SPRITES: 'readonly',   // generated by tools/sprites/build.py
  NavMusic: 'readonly',      // frontend/web/music.js
  NavModule: 'readonly',     // the Emscripten module, built into nav.js
};

export default [
  {
    ignores: ['frontend/web/nav.js', 'build*/**', 'dist/**'],
  },
  {
    files: ['frontend/web/*.js'],
    languageOptions: {
      ecmaVersion: 2020,
      sourceType: 'script',
      globals: { ...browser, ...own },
    },
    linterOptions: { reportUnusedDisableDirectives: true },
    rules: {
      // The ones that catch a typo before a player does.
      'no-undef': 'error',
      'no-unused-vars': ['error', { args: 'none', caughtErrors: 'none' }],
      'no-redeclare': 'error',
      'no-dupe-keys': 'error',
      'no-dupe-args': 'error',
      'no-dupe-else-if': 'error',
      'no-duplicate-case': 'error',
      'no-unreachable': 'error',
      'no-fallthrough': 'error',
      'no-cond-assign': 'error',
      'no-self-compare': 'error',
      'no-self-assign': 'error',
      'no-constant-condition': 'error',
      'no-sparse-arrays': 'error',
      'no-func-assign': 'error',
      'no-import-assign': 'error',
      'no-obj-calls': 'error',
      'no-unsafe-negation': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',
      'no-compare-neg-zero': 'error',
      'getter-return': 'error',
    },
  },
];
