#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Turns the text pixel art in pixels.py into two things.

  frontend/web/sprites.js   what the browser build draws from
  docs/media/sprites.png    a contact sheet, for looking at the art

Run it after editing pixels.py:

    python3 tools/sprites/build.py

The JS payload is deliberately compact: one palette per sprite and one string
of 256 index characters, rather than 41 base64 PNGs. It costs ~20 KB instead of
~200 KB, and — the part that matters — it stays diffable, so a reviewer sees
which pixels changed instead of "binary file differs".
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
sys.path.insert(0, HERE)

from pixels import SPRITES, W, H  # noqa: E402

# Index alphabet for the packed rows. '.' stays transparent.
ALPHABET = '0123456789abcdefghijklmnopqrstuv'

# The order sprites appear on the contact sheet, grouped so the sheet reads as
# terrain / items / heroes / bestiary rather than as one alphabetical wall.
GROUPS = [
    ('Terrain', ['wall', 'floor', 'water', 'chasm', 'door', 'door_open',
                 'stairs_down', 'stairs_up', 'altar', 'fire']),
    ('Items', ['item_weapon', 'item_armor', 'item_amulet', 'item_potion',
               'item_scroll', 'item_food', 'item_gold', 'item_needle']),
    ('Heroes', ['hero_vityaz', 'hero_vedun', 'hero_tat', 'hero_znahar',
                'hero_kuznets', 'hero_bogatyr']),
    ('Pogost', ['anchutka', 'upyr', 'kikimora', 'bolotnik']),
    ('Chernotop', ['mavka', 'poludnitsa', 'volkolak', 'aspid', 'shishiga', 'izbushka']),
    ('Koshchei', ['likho', 'kamennaya', 'nav', 'koldun', 'zmey']),
    ('Peklo', ['chert', 'chugaister', 'ognevik']),
    ('Not always an enemy', ['domovoy']),
    ('Hidden room', ['kot_bayun']),
    ('Guardians 32x32', ['mara', 'viy', 'vodyanoy', 'babayaga',
                         'morozko', 'koschei', 'polozh', 'gorynych']),
]


def pack(sprite):
    """Palette list plus one string of index characters, row-major."""
    keys = sorted(k for k in sprite['palette'] if any(k in r for r in sprite['rows']))
    if len(keys) > len(ALPHABET):
        raise ValueError('palette too large for the index alphabet')
    index = {k: ALPHABET[i] for i, k in enumerate(keys)}
    body = ''.join(index.get(c, '.') for row in sprite['rows'] for c in row)
    return [sprite['palette'][k] for k in keys], body


def emit_js(path):
    out = {}
    for name in sorted(SPRITES):
        colours, body = pack(SPRITES[name])
        entry = {'p': colours, 'd': body}
        if SPRITES[name]['size'] != W:
            entry['s'] = SPRITES[name]['size']
        if SPRITES[name]['tintable']:
            entry['t'] = 1
        out[name] = entry

    payload = {'size': W, 'sprites': out}
    with open(path, 'w', encoding='utf-8') as f:
        f.write('// SPDX-License-Identifier: MIT\n')
        f.write('// Generated by tools/sprites/build.py from tools/sprites/pixels.py.\n')
        f.write('// Do not edit by hand: edit the pixel art and rebuild.\n')
        f.write('//\n')
        f.write('// Each sprite is a palette (p) and %d index characters (d),\n' % (W * H))
        f.write("// row-major, '.' meaning transparent. t:1 means the renderer may\n")
        f.write('// tint it with the colour of the current belt.\n')
        f.write('window.NAV_SPRITES = ')
        json.dump(payload, f, ensure_ascii=False, separators=(',', ':'), sort_keys=True)
        f.write(';\n')
    return os.path.getsize(path)


# --- contact sheet ---------------------------------------------------------

def rgb(hex_colour):
    h = hex_colour.lstrip('#')
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def draw_sprite(img, sprite, x0, y0, scale):
    """Blits a sprite at `scale`. A 32x32 boss is given half the scale so the
    contact sheet stays a grid of equal cells."""
    if sprite['size'] != W:
        scale = max(1, scale * W // sprite['size'])
    px = img.load()
    for y, row in enumerate(sprite['rows']):
        for x, c in enumerate(row):
            if c == '.':
                continue
            col = rgb(sprite['palette'][c])
            for dy in range(scale):
                for dx in range(scale):
                    px[x0 + x * scale + dx, y0 + y * scale + dy] = col


def emit_sheet(path, scale=4):
    from PIL import Image, ImageDraw

    pad, gap, label_h, head_h = 16, 10, 12, 22
    cell = W * scale
    cols = max(len(names) for _, names in GROUPS)
    width = pad * 2 + cols * cell + (cols - 1) * gap
    height = pad
    for _, names in GROUPS:
        height += head_h + cell + label_h + gap
    height += pad

    img = Image.new('RGB', (width, height), (18, 18, 22))
    draw = ImageDraw.Draw(img)

    y = pad
    for title, names in GROUPS:
        draw.text((pad, y + 4), title.upper(), fill=(150, 140, 110))
        y += head_h
        for i, name in enumerate(names):
            x = pad + i * (cell + gap)
            draw.rectangle([x - 1, y - 1, x + cell, y + cell], outline=(50, 50, 58))
            draw_sprite(img, SPRITES[name], x, y, scale)
            draw.text((x, y + cell + 2), name[:11], fill=(130, 130, 140))
        y += cell + label_h + gap

    img.save(path)
    return img.size


def main():
    missing = set()
    for _, names in GROUPS:
        missing |= {n for n in names if n not in SPRITES}
    if missing:
        raise SystemExit('contact sheet lists unknown sprites: %s' % sorted(missing))
    listed = {n for _, names in GROUPS for n in names}
    unlisted = set(SPRITES) - listed
    if unlisted:
        raise SystemExit('sprites missing from the contact sheet: %s' % sorted(unlisted))

    js = os.path.join(ROOT, 'frontend', 'web', 'sprites.js')
    size = emit_js(js)
    print('%-40s %6.1f KB' % (os.path.relpath(js, ROOT), size / 1024))

    # The contact sheet is for human eyes only, so a machine without Pillow
    # still gets the file the build actually needs.
    sheet = os.path.join(ROOT, 'docs', 'media', 'sprites.png')
    try:
        import PIL  # noqa: F401
    except ImportError:
        print('%-40s skipped (no Pillow)' % os.path.relpath(sheet, ROOT))
    else:
        os.makedirs(os.path.dirname(sheet), exist_ok=True)
        dims = emit_sheet(sheet)
        print('%-40s %dx%d' % (os.path.relpath(sheet, ROOT), dims[0], dims[1]))
    print('%d sprites, %dx%d each' % (len(SPRITES), W, H))


if __name__ == '__main__':
    main()
